### ISSUE TITLE
Come up with a Geeky name

### ISSUE THREAD

**Issue by Z-Shang** [Z-Shang/FATE-Another-Text-Editor#1]
YATE?
Maybe something better :(

**Comment by hczhcz** [comment]
How about FATE (F***ing Another Text Editor)? (逃

**Comment by Z-Shang** [comment]
@hczhcz Fate / Another Text Editor （花式递归

**Comment by Z-Shang** [comment]
大家已经研究决定了，就叫 FATE / Another Text Editor 了
我们就不要念诗直接填坑吧（误
