### ISSUE TITLE
Structure Design

### ISSUE THREAD

**Issue by Z-Shang** [Z-Shang/FATE-Another-Text-Editor#2]
Something like this?

Text Editor
        |
Keyboard
        |
Static Analysis

**Comment by Z-Shang** [comment]
According to the design of VIM's and Atom's editor, we should parse the input file into some kind of text objects, then apply corresponding style to them and arrange them into the editor part.

Then there will be a functions in the static analysis part doing:
String => [TextObject]

**Comment by dsh0416** [comment]
Should we make static analysis as a part of plugin?

**Comment by Z-Shang** [comment]
@dsh0416 Nah I don't think so, it is the base of the built-in keyboard and syntax highlighting...
We can make the static analysis engine a built-in part, and static analysis module for different languages as plugins

**Comment by Z-Shang** [comment]
Well I've moved the static analysis part to a separated repo: https://github.com/Z-Shang/fate-static-analysis
