### ISSUE TITLE
Probably the default built-in font

### ISSUE THREAD

**Issue by Z-Shang** [Z-Shang/FATE-Another-Text-Editor#7]
http://be5invis.github.io/Iosevka/

I think a thin font could be great on small screen (especially when about 40% of the screen are taken by keyboard and whatever else)

**Comment by dsh0416** [comment]
I agree with this idea. One of the problems is that built-in keyboard can only code in English, so that this font may work very good.

**Comment by Z-Shang** [comment]
@dsh0416 then let's try it out

**Comment by Z-Shang** [comment]
<img width="1440" alt="screen shot 2015-12-23 at 9 12 38 am" src="https://cloud.githubusercontent.com/assets/859939/11973754/83448a04-a955-11e5-87d4-e6d8e4ccac05.png">
it works great
